### ISSUE TITLE
Location data for NL address is incorrect

### ISSUE THREAD

**Issue by PatrickA-RiseVision** [Rise-Vision/rise-data-weather#60]
### What is the expected behavior?
Weather component uses Display Address or Company Address to obtain local weather.

### What is the actual behavior?
For NL addresses, when the State field is filled, the location data is incorrect.

### What steps can be taken to replicate the problem?
We encountered this with a specific example address.  I'll share the links in the card.

**Comment by alex-deaconu** [comment]
@PatrickA-RiseVision a fix for this issue has been released. To confirm, we found an improved way to encode the address in our requests to the Weather provider, and this should reduce the amount of issues generated by incorrect address responses.

Please let us know if you encounter any further issues related to addresses. Thanks!
