### ISSUE TITLE
Using Rise Vision Anywhere, Weather shows as Fahrenheit despite being set as Celsius

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-data-weather#70]
### What is the expected behavior?
When you set the temperature to show in Celsius, it should show in Celsius in Rise Vision Anywhere.

### What is the actual behavior?
In Rise Vision Anywhere, it is showing in Fahrenheit despite being set in Celsius.

### What steps can be taken to replicate the problem?
Use this Schedule: https://preview.risevision.com/?type=sharedschedule&id=dc71a07e-bccc-4c3f-b22e-7306b8b29ffb, and notice that the weather shows in Fahrenheit despite being set in the Presentation in Celsius.

**Comment by alex-deaconu** [comment]
@robb-price we have deployed a fix for this. The weather should now be configured correctly. Thanks!
