### ISSUE TITLE
Certain addresses are not returning the correct weather information

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-data-weather#74]
### What is the expected behavior?
As long as the weather for the Display and/or Company is accurate, it should show the correct weather.

### What is the actual behavior?
800 Eagle Drive, Argyle Texas 76226 is not showing the correct weather in the Weather Component. According to @ezequielc , "There are some inconsistencies between production and staging environments"

### What steps can be taken to replicate the problem? 
Set the Company and/or Display address to be 800 Eagle Drive, Argyle Texas 76226, and play a Presentation that displays weather.

**Comment by olegrise** [comment]
FYI> It seems that the issue is cause by this line in the presentation https://github.com/Rise-Vision/html-template-library/commit/3e8ade0e172e9f21be005f4f30ea39170018f163#diff-1169760f1347ab2fac8f4be2f1d2b260R32, not the weather component. This line should be commented out.

**Comment by robb-price** [comment]
Another Address giving this error is: 885 railroad street, brookings, oregon, 97415

**Comment by stulees** [comment]
@robb-price Can you provide the specific template that the above address failed? Is it happening with any template that has weather component?

@mmeiers Based on our defect spreadsheet, you fixed a template (see Olegs previous comment) [back in july](https://www.screencast.com/t/U0mbYid1LtX) that fixed the issue. Do you know if the same fix should have been applied to other templates with weather? Thanks

**Comment by mmeiers** [comment]
@robb-price @stulees Ya I'm not sure what happened but I see the same issue in this Template. 

I'll do a once over on templates that have weather, but @robb-price can you please tell me the other specific ones that have the issues I'm doubtful its everyone.

https://github.com/Rise-Vision/html-template-library/blob/00aca403ea59936bb6404f3d0beed8204f21854c/weather-chart/src/template.html#L76

**Comment by mmeiers** [comment]
@robb-price @stulees @olegrise this is fixed. I identified 10 templates that had the full-address attribute in them and remove them. I test the template mentioned above (weather chart) along with a handful of others to verify it changed based on my display address.

**Comment by kaden-rise** [comment]
@mmeiers Not sure if this is fixed yet. 885 railroad street, brookings, oregon, 97415 is still not returning the correct weather data.
![image](https://user-images.githubusercontent.com/33877348/105058974-072b2780-5a34-11eb-9ec4-9a2316ff2b9b.png)
![image](https://user-images.githubusercontent.com/33877348/105059029-19a56100-5a34-11eb-8a8f-7956d6d1e114.png)
![image](https://user-images.githubusercontent.com/33877348/105059140-35106c00-5a34-11eb-830a-71f5865b3044.png)
